version: '2'

services:
  ldap:
    container_name: ldap
    build:
      context: ./ldap
    ports:
      - "10389:10389"
  keycloack:
    container_name: keycloack
    image:  jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=123
    volumes:
      - dados-keycloak:/tmp
    ports:
      - "8080:8080"

volumes:
  dados-keycloak:
    external: true
