version: '2'

services:
  ldap:
    container_name: ldap
    build:
      context: ./ldap
    ports:
      - "10389:10389"
  keycloack:
    container_name: keycloack
    build:
      context: ./keycloack
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=123
      - KEYCLOAK_IMPORT=/tmp/example-realm.json
    volumes:
      - dados-keycloak:/tmp
      - ./keycloack/realm-export.json:/tmp/tmp/example-realm.json
    ports:
      - "8080:8080"

volumes:
  dados-keycloak:
    external: false
